FROM node:14

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
 
WORKDIR /usr/src/app
 
COPY package*.json ./
 
RUN npm install
 
COPY . .

EXPOSE 8000

ENV DATABASE_URL=mongodb+srv://parthm:5EHgbEMwUrI1maI0@cluster0.4wfck.mongodb.net/impress?retryWrites=true&w=majority?authSource=admin

CMD ["npm", "run", "start"]